version: '3.9'

services:

  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - front
    # networks:
    #   - external_network

  front:
    build: frontend/.
    ports:
      - '3000:3000'
    # networks:
    #   - external_network

  back:
    build: backend/.
    ports:
      - '8080:80'
    depends_on:
      - db
    # networks:
    #   - internal_network
    #   - external_network

  db:
    image: postgres:14-alpine
    # restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./backend/db_data:/var/lib/postgresql/data
    # networks:
    #   - internal_network

volumes:
  db_data:

# networks:
#   internal_network:
#   external_network: