version: '3.9'

services:
  nginx:
    build:
      context: ./config
      args:
        - UPSTREAM_HOST=${UPSTREAM_HOST}
    env_file:
      - .env
    ports:
      - '80:80'
    depends_on:
      - front
    networks:
      - external_network

  front:
    build: frontend/.
    env_file:
      - .env
    ports:
      - '3000:3000'
    networks:
      - external_network

  back:
    build: backend/.
    env_file:
      - .env
    ports:
      - '8080:80'
    depends_on:
      - db
    networks:
      - internal_network
      - external_network

  db:
    image: postgres:14-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - ./backend/db_data:/var/lib/postgresql/data
    networks:
      - internal_network

networks:
  internal_network:
  external_network: