version: '3.9'


services:
#   web:
#     build: .
#     ports:
#       - "8000:8000"
#     environment:
#       POSTGRES_URL: jdbc:postgresql://host.docker.internal:5432/postgres
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#     depends_on:
#       - db

  db:
    image: postgres:14-alpine
    # restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ../backend/db_data:/var/lib/postgresql/data

volumes:
  db_data:   