version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      POSTGRES_URL: jdbc:postgresql://host.docker.internal:5432/conference_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Welcome