name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main
      - portfolio

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push Docker images
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_REGISTRY_URI }}
        docker-compose build
        docker images
        docker tag react-project-front:latest ${{ secrets.AWS_ECR_REGISTRY_URI }}/react-project-front:latest
        docker push ${{ secrets.AWS_ECR_REGISTRY_URI }}/react-project-front:latest


    - name: Deploy to Elastic Beanstalk
      run: |
        eb init -r ${{ secrets.AWS_REGION }} -p docker {{ secrets.BEANSTALK_APP_NAME }}
        eb use {{ secrets.BEANSTALK_ENV_NAME }}
        eb deploy